# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Hemalatha Bhaskar
# Description of the Site
description: Data Analyst Portfolio
# URL of Image of the Site
site-image: /assets/images/meta.jpg

# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://www.gauri.com/wp-content/uploads/Business-Intelligence-and-Analytics.jpeg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: hemastays@gmail.com
#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
linkedin_username: hemalatha-bhaskar
github_username:  hemabhaskar
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Hemalatha Bhaskar

# Name of the Author
author-name: Hemalatha Bhaskar
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/hemabhaskar/portfolio/gh-pages/assets/images/profile.jpeg
# 60 Words About the Author
author-about: I embarked on my journey into data analysis during my tenure in the banking sector, where I discovered my passion for leveraging technology to derive insights and solve complex challenges. What initially intrigued me about data was its transformative potential, allowing me to uncover hidden patterns and trends that drive informed decision-making. My interest in data analytics lies in its power to drive strategic initiatives and enhance operational efficiency. Through my experience, I've honed my skills in data analysis, process improvement, and multitasking, enabling me to create strategic communication materials and track/analyze KPIs for Business Units with a keen focus on customer needs.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/hemabhaskar

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "project/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
